import { NextResponse } from "next/server";
import { getAuthUserFromCookies } from "@/lib/auth";
import { generateInviteText } from "@/lib/ai";
import { isRateLimited, getClientIp } from "@/lib/rate-limit";
import { prisma } from "@/lib/prisma";
import { getEffectivePlan, PLAN_LIMITS } from "@/lib/plan-limits";
import { z } from "zod";

const schema = z.object({
  eventTitle:  z.string().min(1).max(200),
  eventDate:   z.string().max(100),
  eventTime:   z.string().max(20),
  location:    z.string().max(300),
  description: z.string().max(2000),
  category:    z.string().max(50),
  dressCode:   z.string().max(100).optional(),
  tone:        z.enum(["formal", "casual", "fun", "elegant"]).default("elegant"),
});

export async function POST(request: Request) {
  try {
    // IP-level burst protection
    if (await isRateLimited(`ai-invite:${getClientIp(request)}`, 20, 60 * 60 * 1000)) {
      return NextResponse.json({ error: "Too many requests. Please try again later." }, { status: 429 });
    }

    const user = await getAuthUserFromCookies(request);
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    // ── AI processing consent check ────────────────────────────────────────────
    const aiConsent = await prisma.consentRecord.findFirst({
      where: { userId: user.userId, type: "AI_PROCESSING" },
    });
    if (!aiConsent) {
      return NextResponse.json(
        { error: "AI_CONSENT_REQUIRED", code: "AI_CONSENT_REQUIRED" },
        { status: 403 },
      );
    }

    // ── Monthly per-plan quota ─────────────────────────────────────────────────
    const fullUser = await prisma.user.findUnique({
      where: { id: user.userId },
      select: {
        plan: true, planExpiresAt: true, role: true,
        aiGenerationsUsed: true, aiGenerationsResetAt: true,
      },
    });

    const effectivePlan = getEffectivePlan(fullUser?.plan ?? "FREE", fullUser?.planExpiresAt, fullUser?.role);
    const aiLimit       = PLAN_LIMITS[effectivePlan].aiGenerations;
    const now           = new Date();

    // Determine the start of next calendar month to use as the reset boundary.
    // Storing a concrete Date prevents string/timezone drift issues.
    const nextMonthStart = new Date(now.getFullYear(), now.getMonth() + 1, 1);

    const windowExpired = !fullUser?.aiGenerationsResetAt || fullUser.aiGenerationsResetAt <= now;

    if (windowExpired) {
      // New window — reset counter
      await prisma.user.update({
        where: { id: user.userId },
        data:  { aiGenerationsUsed: 0, aiGenerationsResetAt: nextMonthStart },
      });
    } else if (aiLimit !== Infinity && (fullUser?.aiGenerationsUsed ?? 0) >= aiLimit) {
      return NextResponse.json({
        error: `Your plan includes ${aiLimit} AI invite generation${aiLimit !== 1 ? "s" : ""} per month. Upgrade for more.`,
        code:  "AI_QUOTA_EXCEEDED",
      }, { status: 403 });
    }

    const body = await request.json();
    const parsed = schema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 });
    }

    const inviteText = await generateInviteText({ ...parsed.data, hostName: user.name });

    // Increment usage counter before responding so quota is enforced on retry
    await prisma.user.update({
      where: { id: user.userId },
      data:  { aiGenerationsUsed: { increment: 1 } },
    }).catch(err => console.error("[ai] failed to increment aiGenerationsUsed:", err));

    return NextResponse.json({
      data: { inviteText },
      // PDPA / B10 disclosure: inform the client that event details were sent
      // to a third-party AI processor so they can surface this to end users.
      aiDisclosure: "Invite text was generated by Anthropic Claude. Your event details were sent to Anthropic's API to produce this text.",
    });
  } catch (error) {
    console.error("AI generate invite error:", error);
    return NextResponse.json({ error: "Failed to generate invite text" }, { status: 500 });
  }
}
